### ISSUE TITLE
fix http://tech.finn.no/2012/07/25/the-ultimate-view-tiles-3/ 

### ISSUE THREAD

**Issue by michaelsembwever** [finn-no/tech.finn.no#17] opened 2014-11-18 16:56 UTC
this post was the most popular (by order of magnitude, or two) post the website.
i would not have voted for switching the site over until it has been fixed.

currently the page is completely blank.

**Comment by Andersos** [comment] 2014-11-18 17:05
I am working on making the posts look better in #9.

We could consider merging the pull request as is now so there would at least be something there.
There is lots of markup that is different. Im not familiar with the conversion tool that was used but I have been trying to manually edit the post in question.

**Comment by michaelsembwever** [comment] 2014-11-18 17:11
yes, something would be better than nothing :-)
 thanks.

**Comment by Andersos** [comment] 2014-11-19 10:12
Duplicate of #5

**Closed as completed by Andersos** 2014-11-19 10:12 UTC
Labels: duplicate
